name: bicepBuild

on:
  push:
    paths:
      - VNETMaxAddressSpaces.bicep

  workflow_dispatch:

jobs:
  BicepBuild:
    name: Bicep Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Azure CLI Action
        uses: Azure/cli@v1
        with:
          inlineScript: bicep install --version v0.4.613
              
      - name: Update-bicep-file-targetscope
        run: |
          var="targetScope = 'subscription'"
          sed -i "1s/.*/$var/" VNETMaxAddressSpaces.bicep

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./VNETMaxAddressSpaces.bicep
          outputFilePath: ./VNETMaxAddressSpaces-Sub.json

      - name: Update-bicep-file-targetscope
        run: |
          var="targetScope = 'managementGroup'"
          sed -i "1s/.*/$var/" VNETMaxAddressSpaces.bicep

      - name: bicep-build-output
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./VNETMaxAddressSpaces.bicep
          outputFilePath: ./VNETMaxAddressSpaces-MgmtGrp.json

      - name: Commit 
        run: |
          git config --global user.name 'PieterbasNagengast'
          git add VNETMaxAddressSpaces-MgmtGrp.json
          git add VNETMaxAddressSpaces-Sub.json
          git commit -am "Auto commit by Github Action"
          git push
